bencheeorg/benchee

lib/benchee/formatters/console.ex
test/benchee/formatters/console_test.exs

Makes the Console formatter increase the label column width if any test name is longer than 29 characters/graphemes.
Fixes https://github.com/PragTob/benchee/issues/11
Do we want to keep the default/minimum 30 character width, or remove/reduce it?
Feedback is appreciated.

Dynamic label width

---

mix.exs
test/benchee/benchmark_test.exs
test/support/test_helpers.ex

* On overloaded/slower systems it seems the tests are flaky,
adjust some numbers a bit and add a retrying helper that
gives a test the chance to execute 5 times before failing it
* makes for i in {1..8}; do mix test test/benchee/benchmark_test.exs & done
constantly succeed on my system whereas before it would fail constantly
Fixes #12 
@alvinlindstam: wanna have a look/want to try this branch out to see if it works better for you? :)

Introduce retrying helper to deal with flaky tests

---

lib/benchee.ex
lib/benchee/benchmark.ex
lib/benchee/config.ex
lib/benchee/statistics.ex
samples/parallel_process.exs
test/benchee/benchmark_test.exs
test/benchee/statistics_test.exs

Hi!
I really like benchee but wanted to do some parallel benchmarking of certain code. So I added this in a fork, below shows how it works - maybe you'd like it as well.
It does change output of  Benchee.measure from:
`[{"bench", [1,2,3,4]}]`
into:
`[{"bench",[[1,2,3,4],[1,2,3,4]]}]`
Where the list is a list of results from separate processes each containing execution times of the passed function. I needed to do this to calc the ips. So had to modify Statistics.statistics for this as well...
regards,
Leon
--
When passing a flag parallel with value >1 then multiple processes
will be handled for benchmarking provided function.
For example:
```
iex> Benchee.run %{parallel: 5, time: 10},
[{"five", fn -> :timer.sleep(1000) end}]
Benchmarking name: five, parallel: 5, time: 10.0, warmup: 2.0... …
```

Add parallel benchmarking capability.

---

test/benchee_test.exs

This test broke on my machine by reaching 12K for some runs. This commit allows for that, and simplifies the regex a bit.

Allow "roughly 10K" to include 12K

---

lib/benchee/formatters/console.ex
lib/benchee/formatters/unit.ex
lib/benchee/formatters/unit/count.ex
lib/benchee/formatters/unit/duration.ex
test/benchee/formatters/console_test.exs
test/benchee/formatters/unit/count_test.exs
test/benchee/formatters/unit/duration_test.exs
test/benchee_test.exs

Integrates unit scaling into the Console formatter (solution for #27)
Features:
- always scales results
- always uses "short" format, e.g. `M` for `Million`
- adds a space between the value and the unit label to match previous output, e.g. `10 μs`
- chooses the "best" unit for a column, and uses that unit for all values
- maintains hard-coded float precision
- adds the ability to scale a value to a specified unit
- adds an improved failure message for column width testing:
Limitations:
- has no option for disabling scaling
- has no option for using a "long" label

Add unit scaling to Console formatter

---

CHANGELOG.md
lib/benchee/config.ex
lib/benchee/formatters/console.ex
lib/benchee/formatters/unit.ex
lib/benchee/formatters/unit/count.ex
lib/benchee/formatters/unit/duration.ex
samples/unit_scaling.exs
samples/unit_scaling_smallest_vs_none.exs
test/benchee/benchmark_test.exs
test/benchee/formatters/console_test.exs
test/benchee/formatters/unit/count_test.exs
test/benchee/formatters/unit/duration_test.exs

Aims to tackle #31 
So far:
* option to scale to a base unit (aka no scaling)
Needs to:
PR opened for early feedback :)

Configure unit selection

---

README.md
lib/benchee/config.ex

- edits for readability, typos in Benchee.Config
- add unit_scaling option summary to README, and update the sample
output to reflect default scaling to ms

Edits to unit scaling docs

---

lib/benchee/conversion/count.ex
lib/benchee/conversion/duration.ex
lib/benchee/conversion/format.ex
lib/benchee/conversion/scale.ex
lib/benchee/conversion/unit.ex
test/benchee/conversion/count_test.exs
test/benchee/conversion/duration_test.exs

This is the general PoC of what I meant/wanted to do. Instead
of passing `:billion`/`;thousand` etc. around let's use the
real units! I think this brings some benefits and I'd be intrigued
to see what @wasnotrice thinks. Pushing this for review, let's see
how much further I can take this :)
Seems like it could help get rid of some code
A PR based on a PR ( #40 ) that based on another PR... PRCeption!
Todo here:

Proof of Concept use Unit struct more (acceptance tests passing)

---

lib/benchee/conversion/count.ex
lib/benchee/conversion/duration.ex
lib/benchee/conversion/format.ex
lib/benchee/conversion/scale.ex
lib/benchee/conversion/unit.ex
test/benchee/conversion/count_test.exs
test/benchee/conversion/duration_test.exs

This was just an experiment, but I really like how it turned out, so I'm opening this PR for review. Note that it is based on #39, because it is an extension of that basic refactoring.
- converts units from plain maps to `Unit` structs
- remove `label/1`, `magnitude/1`, `separator/0` functions from `Count` and `Duration`
- add label and magnitude functionality to the Unit struct, as it better fits there anyway
- retain the option for a module like `Count` to define a `separator/0` function, but if not, just use a space

Use Unit struct, and hang Unit functionality there

---

lib/benchee/conversion/deviation_percent.ex
lib/benchee/formatters/console.ex
test/benchee/conversion/deviation_percent_test.exs

* didn't call it just percent as the deviation and +- part of it
are rather important and wouldn't want to skip it, but then it's
not a normal percent anymore.
* fixes #38 
After the excellent work @wasnotrice did on separating scaling and formatting this turned out to be a real piece of cake and delight :clap:

Implement DeviationPercent unit

---

lib/benchee/system.ex
test/benchee/system_test.exs

I remembered that we wanted to add some tests for the error handling in
`Benchee.System.system_cmd/2`, so I went ahead and refactored that so
we could add those tests.

Add tests for error handling in `System.system_cmd`

---

CHANGELOG.md
lib/benchee.ex
lib/benchee/benchmark.ex
lib/benchee/configuration.ex
test/benchee/benchmark_test.exs
test/benchee/configuration_test.exs
test/benchee/system_test.exs
test/benchee_test.exs

Fixes #83 
Builds on #84 
Helps with #34 
Allow atoms but convert them to strings. Why? Because I really don't wanna see 2 things in the output that look exactly the same and not be able to distinguish them. Furthermore, for plugins it's better if they can consistently assume strings as the names for jobs and inputs and don't have to deal with atom shenanigans :)

Allow atoms as names in jobs and inputs

---

lib/benchee/benchmark.ex
lib/benchee/benchmark/scenario.ex
lib/benchee/suite.ex
test/benchee/benchmark_test.exs

This commit introduces a new struct representing a single thing to
benchmark, which we're calling a Scenario. A scenario represents a
combination of a function and an optional input (or inputs) for that
function. We will also store the results of the benchmark for the scenario
in this struct eventually. Right now the creation of these scenarios for
each job and each input is implemented and tested, but we're not actually
using them yet.

Add Benchmark.Scenario struct

---

lib/benchee/benchmark.ex
lib/benchee/benchmark/runner.ex
lib/benchee/benchmark/scenario.ex
lib/benchee/benchmark/scenario_context.ex
lib/benchee/configuration.ex
lib/benchee/formatters/console.ex
lib/benchee/output/benchmark_printer.ex
lib/benchee/statistics.ex
lib/benchee/suite.ex
test/benchee/benchmark/runner_test.exs
test/benchee/benchmark_test.exs
test/benchee/formatters/console_test.exs
test/benchee/output/benchmark_printer_test.exs
test/benchee/statistics_test.exs
test/benchee/suite_test.exs
test/benchee_test.exs
test/support/fake_benchmark_runner.ex
test/support/test_helpers.ex

Ok, this is a biggie, so I tried to have each commit be a standalone piece that could be reviewed on its own. I took a pretty methodical approach, so hopefully if you follow the commits you'll get a sense of the changes I made at each step.
It still feels a little "incomplete" without the memory usage stuff in there - especially the console formatter - but all tests are passing and it feels to me like it's in a good place now.

Extract runner and move to scenarios

---

lib/benchee/system.ex

When `benchee` is used on hosted CI tool [`Semaphore`](https://semaphoreci.com/) it is failing with:
```
** (MatchError) no match of right hand side value: nil
(benchee) lib/benchee/system.ex:81: Benchee.System.parse_cpu_for/2
(benchee) lib/benchee/system.ex:18: Benchee.System.system/1
...
```
because `cat /proc/cpuinfo` produces:
```
...
model name	: Intel Core Processor (Haswell)
...
```
and regex in `parse_cpu_for(:Linux, raw_output)` expects `model name` to contain `ghz` string.
When `Regex.run` finds no match it returns `nil` and Elixir pattern matching (`=`) expects list so we get `MatchError` exception.
This PR
- relaxes `parse_cpu_for` regex ("ghz" string is not required) and
- gracefully falls back even if CPU model name is not recognized.

Relax CPU info regex

---

lib/benchee/system.ex
test/benchee/system_test.exs

As usual, after a bit of sleep I realized that the functions for
parsing the raw output from `system_cmd/2` was already there, and we
could test those in isolation without having to do much at all.
Resolves #104

Add additional tests for System module

---

test/benchee/system_test.exs

* closes #107
* should remove that flakyness for running on some machines

Remove assertion on Mhz, is done in `.parse_cpu_for`

---

lib/benchee/system.ex

This always irked, I think a binary representation is correct as
you know, computers.
The wikipedia article (https://en.wikipedia.org/wiki/Gigabyte)
also claims it:
However, the term is also used in some fields of computer science
and information technology to denote 1073741824 (1024^3 or 2^30)
bytes, particularly for sizes of RAM.
So, I think this is more correct. I also noted that we don't test
that particular part, but that might be for another day :)
-------------------
For reference, on master it claims (for me):
`Available memory: 16.372024 GB`
On this branch it claims:
`Available memory: 15.613578796386719 GB`
Which incidentally is the same my system info reports, no idea why though:

Interpret system returned memory size as binary

---

lib/benchee/statistics.ex
lib/benchee/statistics/mode.ex
test/benchee/statistics/mode_test.exs
test/benchee/statistics_test.exs

Another nice statistics to have handy. Imo could be very useful
for memory measuremnts as I hope that memory usage will often be
very stable so getting the mode should be close to the actual
memory usage.
We also get the `mode_count` for "free` not sure if we should
include it or not (I have never seen it used), but it seems sort
of useful (like for memory usages we could say/include stuff like
60% of all samples were this that helps)

Implement mode in Statistics calculation

---

lib/benchee/formatter.ex
lib/benchee/formatters/console.ex
test/benchee/formatter_test.exs
test/support/fake_formatter.ex

In this commit I'm defining a behaviour for a Benchee Formatter, which
consistes of three functions:
* format/1 which takes a Benchee.Suite struct and formats results
* write/1 which takes the output from format/1 and writes it either to
a file or to the console, and
* output/1 which basically just calls `format/1` and then `write/1` and
returns the Benchee.Suite struct it was given.
I don't see why we can't eventually remove the `output/1` callback from
this behaviour once we've switched over to using `parallel_output/2`
and once we've implemented this behaviour in all the other formatters.
I also wrote a function that can do as much in parallel as possible for
formatting. We can't write the output in parallel, but we can generate
the output in parallel, so we're doing that here.
I …

Define behaviour for a formatter and output in parallel

---

lib/benchee/conversion/memory.ex
lib/benchee/system.ex
test/benchee/conversion/memory_test.exs

https://github.com/PragTob/benchee/issues/121

memory unit formatter

---

lib/benchee/benchmark/runner.ex
lib/benchee/benchmark/scenario_context.ex
test/benchee/benchmark/runner_test.exs
test/benchee_test.exs

Introduced a new `scenario_input` field to keep the value around
as long as we need it as the hooks are run exactly once for each
scenario. Contemplated just naming it `input` but decided it was
too difficult.
As a side effect, creation of the benchmarking function had to be
moved around. It's closer to where it will be used now, which is
good. However, once we pass this on to `before/after_each` there
is a strong possibility it might change as well (as the inputs can
change again).

before_scenario is passed the input and can return a different one

---

lib/benchee/benchmark/runner.ex
lib/benchee/benchmark/scenario_context.ex
test/benchee/benchmark/runner_test.exs
test/benchee_test.exs

Sadly, this breaks our new found great achievement that we have
a benchmarking function that we can reuse. The reason being, that
when before_each can change the input for every invocation - so
the function we create has to be recreated every time.
This could potentially be optimized further, by using `:timer.tc/2`
or be determining if before_* methods are given at all. Plus for
our "repeat n" case, the function could be reused and doesn't have
to be recreated everytime.

before_each gets inputs and passes them on

---

lib/benchee/formatters/console.ex
lib/benchee/statistics.ex
lib/benchee/statistics/percentile.ex
test/benchee/formatters/console_test.exs
test/benchee/statistics/percentile_test.exs
test/benchee_test.exs

Hi all,
Here's a first pass at adding nth percentile calculations for initial review (see #48). Essentially just:
- a percentile function with tests (calculates any percentile value)
- replacing the current median function with the new percentile function (since the median `is` the 50th percentile value)
There are lots of methods for calculating percentile, and I don't know much about the theory. Of the three most accepted, I chose the one that was explained in greatest detail. I left some resources in a comment for further reading, but I feel confident this method is suitable for our purposes, but it would be trivial to replace, or even offer alternate strategies.
This implementation has similar big-O complexity to the current median function (sorting and then traversing the list of …

Add nth percentile calculation

---

lib/benchee/conversion/count.ex
lib/benchee/conversion/duration.ex
lib/benchee/conversion/memory.ex
lib/benchee/conversion/scale.ex
test/benchee_test.exs

* Implements `convert` as part of the behaviour so that everything adopts it
* also makes `convert` work with %Unit{} and the unit atoms (along with it `unit_for`)
* includes a drive by fix for a test that was flaky for me locally when run with `coveralls`

Convert for all

---

lib/benchee/benchmark/runner.ex
test/benchee/benchmark/runner_test.exs
test/benchee_test.exs

Pondered whether after_scenario should behave like before_* i.e.
the input can be altered and passed on. Didn't see much sense
in that though as the last value (global_after_scenario) will go
nowher and the values aren't passed to any benchmarking function.
Also for consistency with `after_each` I decided to just pass them
the output of the last before_scenario (just like all after_each's
just get the return value of the benchmarking function).

after_scenario with inputs implementation

---

README.md

Hi @PragTob, I promised an example of the hooks documentation suggestions I made in #143, so here it is. I tried to name a few more concepts and structure things by Suite/Scenario/Benchmarking rather than by the order in which all the functions appear. I also tried to keep the explanation for each kind of hook brief, with cross-references to sections on arguments/ordering where those confusing parts are explained in more detail. I did not change any of the code examples.
Feel free to take what you like and discard what you don't 😀

Alternate approach to hooks documentation

---

lib/benchee/formatter.ex
lib/benchee/formatters/console.ex
test/benchee_test.exs

Noticed it in the HTML formatter that the output/1 function had
added logic which then wouldn't be called in the new "specify
a formatter as a module and we'll call `format/1` and `output/1`
for you". `output/1` should really only do this, nothing more.
This helps us enforce this and avoid code duplication.

use Formatter to avoid extra logic in `output/1` + repetition

---

README.md
lib/benchee/configuration.ex
lib/benchee/formatters/console.ex
test/benchee/configuration_test.exs
test/benchee/formatters/console_test.exs

Closes #50 
Benchee collects statistics that may not always need to be shown to the general user but could still be beneficial to some. This PR introduces the capability to optionally display these "extended statistics", which consist of: minimum runtime, maximum runtime, mode runtime, and sample size. This PR implements it as a single boolean configuration value that when true will enable the console formatter to output all of the mentioned extended statistics. False, obviously will not display them. 
* Should displaying these be turned off by default, as it is implemented in this PR?
* Right now I do not have any formatting for sample size, merely just running the number through ```to_string/1``` should this be formatted perhaps?
* I felt that both the regular scenario and extended …

Implementing extended options for console formatter

---

.gitignore
.tool-versions

Interested to see how people feel about this.
a) Not everyone uses asdf so not directly affected
b) if you know where to look (travis) you already have a place to
get an overview of supported versions. Should also be in the
README but is probably missing atm ;P
c) potentially high churn (ideally it'll be updated rather quickly
for every new elixr/erlang release)
So, does it provide value - yay or nay?

Provide .tool-versions with current go do elixir/erlang versions

---

lib/benchee/formatters/console.ex
lib/benchee/statistics.ex

The following line was originally in #153 and we dropped the type spec cause we couldn't get it to work. It would fail on all Erlang versions that aren't 18.3.
Basically it is the following (the only place where the offending function is called):
```elixir
@spec extended_statistics([Scenario.t], unit_per_statistic, integer)
:: [String.t]
defp extended_statistics(scenarios, units, label_width) do
Enum.map(scenarios, fn(scenario) ->
format_scenario_extended(scenario, units, label_width)
end)
end
@spec format_scenario_extended(Scenario.t, unit_per_statistic, integer)
:: String.t
defp format_scenario_extended(%Scenario{}, %{run_time: run_time_unit}, label_width) do
"~*s~*ts~*ts~*ts~*ts\n"
|> :io_lib.format([lots_of_options])
|> to_string
end
```
We get the following error:
``` …
```

Help! Why doesn't dialyzer like this spec? :(

---

CHANGELOG.md
lib/benchee/benchmark/runner.ex
test/benchee/benchmark/runner_test.exs

Alternative to #167 / builds upon it - new PR as I didn't wanna go and revert the changes. Builds upon it (test and Changelog) :)
Instead of already updating the scenario throughout all the benchmarking, just return the run_times/measurements in the end - which is the perfect moment to `flatten` them and add them to the scenario as a whole. Also seems to simplify some code in some places, however adds an extra argument in some places. We can't get rid off `scenario` though, as it's needed for the function and other data.
Let me know what you think :)

Parallel bug fix alternative

---

.tool-versions
lib/benchee/benchmark/runner.ex
test/benchee/benchmark/runner_test.exs

Backported fix for 0 runtime handling from #168

---

lib/benchee/formatters/tagged_save.ex
test/benchee/formatters/tagged_save_test.exs

Not 100% happy with this implementation. Seems overcomplicated.
I changed the requirements a bit so that we don't create tag-1
but just tag and tag-2. Otherwise it'd be even more involved.
I considered making it more structure that a Tag is a structure
with `%Tag{name: "foo", count: 1}` or something like this.
But that also seemed like a bit of overkill.
So yeah, if you have anything simpler let me know. Otherwise
let me know if you think this is good enough :)
**Attention** 2 commits, first one is the implementation second one is `mix.format`ing it. (better reviewability)

Tagged save numbers

---

lib/benchee/benchmark/runner.ex
test/benchee/benchmark/runner_test.exs

I think `:erlang.process_info(self(), :memory)` was the trick! Using
that function, I got **no** negative values, and relatively consistent
memory usage. This just adds those measured values to our scenarios,
but doesn't do anything with them yet.
Here's a screenshot of the unique values I got after running the test
I added. It seems consistently giving us a highest value of 133952 for
the function we're measuring in the test.
For now I build this on top of #167 to make merging easier later on, so
just check the third commit if you want to see the new stuff.
Encouraging progress!

Measure memory 3

---

.credo.exs
.tool-versions-e
README.md
lib/benchee/benchmark/runner.ex
lib/benchee/configuration.ex
lib/benchee/conversion.ex
lib/benchee/conversion/memory.ex
lib/benchee/conversion/scale.ex
lib/benchee/formatters/console.ex
lib/benchee/formatters/console/helpers.ex
lib/benchee/formatters/console/memory.ex
lib/benchee/formatters/console/run_time.ex
lib/benchee/memory_measure.ex
lib/benchee/statistics.ex
samples/measure_memory.exs
test/benchee/benchmark/runner_test.exs
test/benchee/conversion_test.exs
test/benchee/formatters/console/memory_test.exs
test/benchee/formatters/console/run_time_test.exs
test/benchee/formatters/console_test.exs
test/benchee/memory_measure_test.exs
test/benchee/statistics_test.exs
test/benchee_test.exs
test/test_helper.exs

Ok, at this point a lot is going on here. Right now there are _minimal_ tests on the new behavior, which I've used to refactor the initial messy implementation into something not too bad. At this point, things I still have left to do are:
* rename some functions that still imply relationship to run time measurements
* ~~add a bunch more tests for new behavior~~
* ~~document this fully~~
* ~~add extended output for memory usage stats if requested~~
The major things I've done in this PR so far are:
* add @michalmuskala's new memory measurement module
* add memory measurement to the console formatter
* split the console formatter into three modules - one for run times, one for memory, and one for shared functions between the two of them
So, right now just about everything is working (except …

Calculate memory stats

---

lib/benchee/configuration.ex

This way folks won't think things just aren't working, and will know to
upgrade their version of OTP to something newer.
Resolves #194

Add warning for memory measurement on OTP 18

---

lib/benchee/benchmark/runner.ex

Sadly this isn't really testable in our current structure,
but the test isn't really worth that re-architecturing I think sooo
Also of course ideally we wouldn't need this - but this is a good
guard for now to not let bad values through.

Drop negative memory measurements

---

lib/benchee/memory_measure.ex
test/benchee/memory_measure_test.exs

Or is there a reason we need this that I'm missing? :)
(this PR is more of a question illustrated with code)

We only ever call MemoryMeasure with a single function as argument

---

appveyor.yml
test/benchee/benchmark/runner_test.exs
test/benchee_test.exs
test/test_helper.exs

First shot at an appveyor configuration

---

README.md
lib/benchee/benchmark/measurer.ex
lib/benchee/benchmark/measurer/memory.ex
lib/benchee/benchmark/measurer/time.ex
lib/benchee/benchmark/runner.ex
lib/benchee/configuration.ex
lib/benchee/formatters/console.ex
lib/benchee/formatters/console/memory.ex
lib/benchee/formatters/console/run_time.ex
lib/benchee/output/benchmark_printer.ex
lib/benchee/statistics.ex
samples/macro_benchmark.exs
samples/measure_memory.exs
test/benchee/benchmark/measurer/memory.ex
test/benchee/benchmark/runner_test.exs
test/benchee/formatters/console/memory_test.exs
test/benchee/formatters/console/run_time_test.exs
test/benchee/formatters/console_test.exs
test/benchee/output/benchmark_printer_test.exs
test/benchee/statistics_test.exs
test/benchee_test.exs

Introduces a new `Measurer` behaviour that can be adopted by `Time`
and `Memory` and in the future `Reduction`. Also switches over to
memory having its own configuration for time. Like how this ended up
in general.
This isn't merge ready yet, it's a first implementation already
up for review and CI.
Fixes #202 
Ah yeah, most important proof - it actually fixes the problem - memory measurements don't seem to be impacting runtime measurements anymore:
```
tobi@speedy ~/github/benchee $ mix run samples/run.exs 
Name                  ips        average  deviation         median         99th %
flat_map           2.16 K      463.52 μs    ±10.62%         452 μs         762 μs
map.flatten        1.16 K      863.87 μs    ±16.60%         822 μs     1301.96 μs
Comparison: 
flat_map           2.16 K …
```

First version of separating memory and runtime measurements

---

lib/benchee/benchmark/measure/memory.ex

The erlang gc information seems to report old and young generation
separately.
Here is an example from faulty measurements we used:
```elixir
[
old_heap_block_size: 0,
heap_block_size: 610,
mbuf_size: 77,
recent_size: 0,
stack_size: 14,
old_heap_size: 0, # <--- notice me
heap_size: 540,
bin_vheap_size: 0,
bin_vheap_block_size: 46422,
bin_old_vheap_size: 0,
bin_old_vheap_block_size: 46422
]
[
old_heap_block_size: 2586,
heap_block_size: 1598,
mbuf_size: 0,
recent_size: 198,
stack_size: 14,
old_heap_size: 355, # <--- notice me
heap_size: 275,
bin_vheap_size: 0,
bin_vheap_block_size: 46422,
bin_old_vheap_size: 0,
bin_old_vheap_block_size: 46422
]
```
Notice how `heap_size` got smaller but together with the
`old_heap_size` memory was still consumed?
Yup, that's what we're talking about here. …

Account for the old generation in memory measurements

---

lib/benchee/conversion/scale.ex
lib/benchee/formatters/console/memory.ex
lib/benchee/statistics.ex
samples/memory_breaker.exs
test/benchee/formatters/console/memory_test.exs
test/benchee/statistics_test.exs
test/benchee_test.exs

We hadn't handled the calculation of statistics when given a whole
bunch of 0s, which is a complication since we're doing a lot of
division in there. Technically if we're in a situation where we're
supposed to divide by 0 the answer is Infinity, but instead of
introducing that, for now I'm just returning 0 as well.
Addresses the first reported bug in #213.

Handle calculation of statistics when given 0s

---

.travis.yml
CHANGELOG.md
lib/benchee/benchmark/hooks.ex
lib/benchee/benchmark/measure.ex
lib/benchee/benchmark/measure/memory.ex
lib/benchee/benchmark/measure/native_time.ex
lib/benchee/benchmark/measure/time.ex
lib/benchee/benchmark/repeated_measurement.ex
lib/benchee/benchmark/runner.ex
lib/benchee/benchmark/scenario_context.ex
lib/benchee/configuration.ex
lib/benchee/conversion.ex
lib/benchee/conversion/duration.ex
lib/benchee/formatters/console.ex
lib/benchee/formatters/console/run_time.ex
lib/benchee/output/benchmark_printer.ex
lib/benchee/statistics.ex
samples/fast_functions.exs
samples/memory_breaker.exs
test/benchee/benchmark/repeated_measurement_test.exs
test/benchee/benchmark/runner_test.exs
test/benchee/conversion/duration_test.exs
test/benchee/formatters/console/run_time_test.exs
test/benchee/output/benchmark_printer_test.exs
test/benchee/statistics_test.exs
test/benchee_test.exs
test/test_helper.exs

Fixes #207
* Introduce a separate measurer to use during warmup which uses the native time
* add nano seconds to our list of available units
* change up display of times in places

Measure with best available precision

---

.credo.exs
.exguard.exs
README.md
lib/benchee/benchmark/runner.ex
lib/benchee/benchmark/scenario_context.ex
lib/benchee/configuration.ex
samples/fast_functions.exs
test/benchee/benchmark/runner_test.exs
test/benchee_test.exs

Quite some drive by fixes in here :)
Had to add the configuration option so that it doesn't drive up our test times - these 0.02 seconds add up when you do it a hundred times!
Idea as a follow up: Show the measured overhead in the printed out configuration. That improves discoverability but also adds a place to show that someone has it intentionally turned off (it's opt out). However, that requires moving code around: Either move the printing into the runner (not really the right place) or move the inner part of the runner somewhere else so that it can be called from `Benchmark` and already displayed there and then passed into the runner.
Here it is in action, making it visible that a lot of the function are just optimized by the compiler to return a constant (which is great):
``` …
```

Function call overhead

---

lib/benchee/system.ex

This adds a warning when folks try to run benchmarks in environments
without protocol consolidation enabled.
I have no idea how to test this since you can't turn protocol
consolidation off at runtime, though. I did test this locally, and this
is the output I got:
```
~/sandbox/benchee   Issue-68±  mix run samples/run.exs
Not all of your protocols have been consolidated. In order to achieve the
best possible accuracy for benchmarks, please ensure protocol
consolidation is enabled in your benchmarking environment.
Operating System: macOS"
CPU Information: Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
Number of Available Cores: 4
Available memory: 8 GB
Elixir 1.6.4
Erlang 20.3
Benchmark suite executing with the following configuration:
warmup: 2 s
time: 10 s
memory time: 2 s
parallel: 1 …
```

Add warning when protocols are not consolidated

---

lib/benchee/configuration.ex
lib/benchee/formatters/console.ex
samples/title.exs
test/benchee/formatters/console_test.exs

This adds a configuration option for a `title` key, and also prints the
title in the console formatter if set.
Resolves #208

Add idea of a benchmark title

---

lib/benchee/configuration.ex
lib/benchee/statistics.ex
lib/benchee/suite.ex
test/benchee/configuration_test.exs
test/benchee/statistics_test.exs

Before these were always set to 50 and 99, but now users can customize
the percentiles they want to see in extended statistics. We always need
the 50th percentile to get the median, so even if a user doesn't set
that, it will be calculated anyway.
Resolves #151

Allow for customizable percentiles in extended statistics

---

lib/benchee/benchmark/scenario.ex
lib/benchee/conversion/format.ex
lib/benchee/formatters/console/helpers.ex
lib/benchee/formatters/console/memory.ex
lib/benchee/formatters/console/run_time.ex
test/benchee/formatters/console/memory_test.exs

Removing our faulty `duration_output` and using our specialized `memory_output` seemingly already fixes the problem :sweat_smile: 
Of course ideally we'd fix our memory measurements but that's a whole other topic - being more resilient is a first good step.
If this passes review I'd cherry pick release it as 0.13.2

Memory format crash

---

lib/benchee/benchmark/measure/memory.ex
test/benchee/benchmark/measure/memory_test.exs
test/benchee/benchmark/runner_test.exs
test/benchee_test.exs
test/test_helper.exs

We were somewhat reliably missing the first garbage collection event
because when we spawned our tracer, we were setting the tracing flag in
the function to be executed in our tracer. This means the runner and
tracer were running concurrently for a moment, and the runner hit a GC
threshold before the tracer was able to set the appropriate tracing
flag!
Now we explicitly block the runner from running the function to be run
until the tracing flag is set.
With this patch applied I now see all the GC events that we should see.
Also, I have absolutely no idea how to test this other than the tests we
already had in place.
Resolves #234 and #205 🎉

Fix race condition in spawning tracer process

---

lib/benchee/benchmark/measure/memory.ex
test/benchee/benchmark/measure/memory_test.exs

This will ensure that we're collecting _only_ data that is allocated as
part of the execution of the function we're trying to benchmark. The
downside is that we end up running the function twice - once to
capture the return value and once to measure the memory usage - but
this way we're sure that we're not accidentally counting terms that
weren't directly a result of the function we're measuring.

Remove any bindings to any data allocated during measurement

---

CHANGELOG.md
README.md
lib/benchee.ex
lib/benchee/configuration.ex
lib/benchee/formatter.ex
lib/benchee/formatters/console.ex
lib/benchee/formatters/console/run_time.ex
lib/benchee/formatters/tagged_save.ex
lib/benchee/utility/deep_convert.ex
samples/formatters.exs
samples/run_extended_statistics.exs
test/benchee/configuration_test.exs
test/benchee/formatter_test.exs
test/benchee/formatters/console_test.exs
test/benchee/formatters/tagged_save_test.exs
test/benchee_test.exs
test/support/fake_formatter.ex

**no really ready for review yet just wanted to bring it out here**
* high level integration tests (benchee_test) pass
* still needs to fix existing unit tests and add new ones for what
I added
* also probably move some code around

Formatter option tuples introduction

---

README.md

A tiny PR fixing this link :wink:

Fix a broken link to the measuring memory section

---

lib/benchee/configuration.ex
test/benchee/configuration_test.exs
test/benchee/formatter_test.exs
test/benchee_test.exs
test/support/fake_formatter.ex

Interestingly the bug occurred thanks to our legacy format support.
Can't wait to get rid off it ;)
I changed the code for the formatter test to really make sure that
the same options passed to format/2 are also passed to write/2.
It didn't find the bug as the bug was in Configuration, but I
think it's still an improvement worth keeping.
Once this code is merged, we can delet the one unnecessary line
from the CSV formatter. Already tried it and it worked :tada:

Fix issue of passing nil to formatters (from CSV PR)

---

lib/benchee/formatters/console.ex
lib/benchee/statistics.ex
test/benchee/formatters/console_test.exs
test/benchee/statistics_test.exs

Before every formatter had to call `Statistics.sort` by themselves,
which is unnecessary work for the formatters. I think it comes
from a time where we had maps instead of lists. But now we can
provide an order.
This should also go towards some consistency in which scenarios
are displayed. Moreover we can make `Statistics.sort` private
limiting our possible interaction surface.

Provide a sorted order of scenarios for all formatters

---

lib/benchee/system.ex
test/benchee/system_test.exs

Currently, the only recognized operating systems are macOS, Windows, and
Linux.  If the operating system is not recognized, it is treated as if
is was Linux.  This results in improper reporting and error messages
during a benchee run.
The added code deals with gathering information on a FreeBSD system.

Add FreeBSD to the list of recognized operating systems.

---

lib/benchee/benchmark/scenario.ex

Formatters often have to check whether run time or memory data
was processed - so if data was collected at all and if statistics
have already been generated so that they can be rendered.
This should simplify this/not tie all of them to the internal
data structure.
The decision as made to check directly on statistics to see if
values actually made it into it, rather than just checking the
configuration if it was intended to measure, so that we're sure
that values are there.
This might sound like a check on `Suite` to check if all scenarios
have all data might be a good thing, however mostly formatters
split things by input so it will more often be checked on a
sub set of scenarios or individual scenarios.
This PR doesn't use the function in our formatters yet, to avoid
merge conflicts with …

Add Scenario.data_processed? to simplify checks in formatters

---

.tool-versions
.travis.yml

Having elixir 1.8 installed which was compiled by by otp 20 while
running otp 21 seemed pretty weird.

@devonestes was right, better to make OTP compiled version

---

lib/benchee/benchmark.ex
lib/benchee/benchmark/hooks.ex
lib/benchee/benchmark/repeated_measurement.ex
lib/benchee/benchmark/runner.ex
lib/benchee/conversion.ex
lib/benchee/formatters/console.ex
lib/benchee/formatters/console/memory.ex
lib/benchee/formatters/console/run_time.ex
lib/benchee/formatters/tagged_save.ex
lib/benchee/scenario.ex
lib/benchee/statistics.ex
lib/benchee/suite.ex
test/benchee/benchmark/repeated_measurement_test.exs
test/benchee/benchmark/runner_test.exs
test/benchee/benchmark/scenario_test.exs
test/benchee/benchmark_test.exs
test/benchee/formatters/console/memory_test.exs
test/benchee/formatters/console/run_time_test.exs
test/benchee/formatters/console_test.exs
test/benchee/formatters/tagged_save_test.exs
test/benchee/output/benchmark_printer_test.exs
test/benchee/scenario_loader_test.exs
test/benchee/statistics_test.exs
test/support/test_helpers.ex

Over time Scenario has become one of our most used data structures,
perhaps the most used data structure and the most important one
besides Suite.
I mean of course, because all the important data (as in results)
is kept within a scenario. Even CollectionData is top level.
Makes no sense for Scenario to be scoped under Benchmark, as some
of the changed files also imply (as often it was the only aliased
module that was not under the top level name space)

Promote Scenario to be a top level data structure

---

lib/benchee.ex
lib/benchee/benchmark.ex
lib/benchee/collection_data.ex
lib/benchee/configuration.ex
lib/benchee/conversion/count.ex
lib/benchee/conversion/deviation_percent.ex
lib/benchee/conversion/duration.ex
lib/benchee/conversion/format.ex
lib/benchee/conversion/memory.ex
lib/benchee/conversion/unit.ex
lib/benchee/formatter.ex
lib/benchee/formatters/console.ex
lib/benchee/formatters/console/helpers.ex
lib/benchee/formatters/console/memory.ex
lib/benchee/formatters/console/run_time.ex
lib/benchee/formatters/tagged_save.ex
lib/benchee/scenario.ex
lib/benchee/scenario_loader.ex
lib/benchee/statistics.ex
lib/benchee/suite.ex
lib/benchee/system.ex
lib/benchee/utility/file_creation.ex
lib/benchee/utility/parallel.ex
lib/benchee/utility/repeat_n.ex
test/benchee/statistics_test.exs

* make what we don't want to be used not documented
* delete an apparently unused function in the process
* add some type docs
(inch doesn't seem to recognize some of these changes, if this persists I might file a bug report with them)
feedback probably forth it on whether making all of these private is really a good idea :)

Brush up on the documentation

---

.exguard.exs
lib/benchee/benchmark/repeated_measurement.ex
lib/benchee/formatters/console/helpers.ex
lib/benchee/formatters/console/memory.ex
lib/benchee/formatters/console/run_time.ex
lib/benchee/statistics.ex
samples/fast.exs
samples/run.exs
test/benchee/benchmark/repeated_measurement_test.exs
test/benchee/formatters/console/memory_test.exs
test/benchee/formatters/console/run_time_test.exs
test/benchee/formatters/console_test.exs
test/benchee/statistics_test.exs
test/benchee_test.exs
test/support/bench_keyword.ex

This is done for 2 reasons:
1. support a new feature I really want to have before 1.0/as a
little migration bait which is supposed to show the absolute
difference to the reference scenario/fastest scenario. This
is good to put performance gains into perspective. It's
great if something is 100 times as fast, but if it only
gains me 1 ms in a program that takes 100ms then it's probably
not worth it
2. centralize the calculation of the multiplicator / lesser / more
thing so that not every formatter has to implement that
popular calculation by themselves. This also revealed an
interesting case that I think we're not handling correctly in
the formatters yet that happens when the average is 0.
It took more code than I thought it'd but looking at it I also
wouldn't know where to cut it.
Input …

Relative statistics

---

lib/benchee.ex
lib/benchee/configuration.ex
lib/benchee/formatter.ex
mix.exs

This builds off #255, so that should be reviewed first.
This PR just adds deprecations for the things that we'll be removing in #256 so folks have some help in upgrading before that stuff is removed.

Deprecations

---

lib/benchee.ex
lib/benchee/benchmark.ex
lib/benchee/configuration.ex
lib/benchee/formatter.ex
lib/benchee/formatters/console.ex
test/benchee/configuration_test.exs
test/benchee_test.exs

This builds off of #255, so that should be reviewed first.
This is still missing a comprehensive documentation overhaul, but this should be good enough for a 1.0 release candidate I think. Once that's out and we have an RC, we'll have some time to work on making documentation really good before 1.0 officially happens.
I'm going to open a separate PR that actually deprecates everything that is being removed in here, which we can merge first and release as 0.99.0 so folks have something to help them migrate to 1.0.

Remove all deprecated functionality (i.e. version 1.0!)

---

CHANGELOG.md
lib/benchee/formatters/console/memory.ex
mix.exs
samples/memory_changing.exs
test/benchee/formatters/console/memory_test.exs

Always displayed extended statistics although it shouldn't

Fix memory display extended statistics

---

.travis.yml
lib/benchee/benchmark/function_call_overhead.ex
lib/benchee/benchmark/repeated_measurement.ex
lib/benchee/benchmark/runner.ex
lib/benchee/benchmark/scenario_context.ex
lib/benchee/statistics.ex
lib/statistex.ex
lib/statistex/mode.ex
lib/statistex/percentile.ex
test/benchee/statistics/mode_test.exs
test/benchee/statistics_test.exs
test/statistex/mode_test.exs
test/statistex/percentile_test.exs
test/statistex_test.exs

This is step one where Statistex still lives in benchee. Goal is to have it in `lib` so that it could just be copy and pasted over into its own repository.

Extract Statistex from benchee

---

lib/benchee/benchmark/collect/reductions.ex
lib/benchee/benchmark/runner.ex
lib/benchee/collection_data.ex
lib/benchee/configuration.ex
lib/benchee/conversion.ex
lib/benchee/conversion/scale.ex
lib/benchee/formatters/console.ex
lib/benchee/formatters/console/reductions.ex
lib/benchee/output/benchmark_printer.ex
lib/benchee/relative_statistics.ex
lib/benchee/scenario.ex
lib/benchee/statistics.ex
lib/benchee/system.ex
samples/measure_reductions.exs
test/benchee/benchmark/collect/reductions_test.exs
test/benchee/benchmark/runner_test.exs
test/benchee/formatters/console/reductions_test.exs
test/benchee/output/benchmark_printer_test.exs
test/benchee_test.exs

This has been sitting on my machine like half done for a month or so, and I finally finished it!
This adds reduction counting, which behaves almost exactly like memory measurement. This should finally allow folks to do really high-quality performance testing that won't be affected by all the other random stuff that can affect clock time.
It's still a little rough, but it works!

Add reduction counting

---

README.md
lib/benchee.ex
lib/benchee/configuration.ex
lib/benchee/output/profile_printer.ex
lib/benchee/profile.ex
samples/fast_with_profiling.ex
test/benchee/profile_test.exs
test/benchee_test.exs
test/support/fake_profile_printer.ex

Enable profiling after benchmarking with the addition of a `profile`
configuration option. It's a map containing:
* `profile_after`, which if set to `true` will enable the profiling
* `profiler`, to set the buit-in profiler to use (:cprof, :eprof, :fprof)
* `profiler_opts`, a list of profiler-specific options to pass to the profiler
Closes #250.
TO-DO:

Add support for built-in profilers

---

lib/benchee/benchmark/collect/memory.ex

Fixes deprecation warning:
`System.stacktrace/0 is deprecated, use __STACKTRACE__ instead`

fix: stacktrace deprecation

---

.github/workflows/main.yml

* https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
* https://github.com/bencheeorg/benchee/runs/1866359293

Try and fix windows CI

---

lib/benchee/output/benchmark_printer.ex

It confuses me because it looks like map_100 is trimmed.
Benchmarking first: Map.get with input map_100...
Now it looks:
Benchmarking first: Map.get with input map_100 ...

Add space before ellipsis

---

CHANGELOG.md
lib/benchee/benchmark.ex
lib/benchee/output/benchmark_printer.ex
test/benchee/profile_test.exs
test/benchee_test.exs
test/support/test_helpers.ex

#358 but with a high level test and changelog :)

Eval function notice

---

lib/benchee/system.ex
lib/benchee/utility/erlang_version.ex

Follow up to https://github.com/bencheeorg/benchee/pull/368
Still fixes #367 
* still print an error
* fix actual versions comparisons

Extension: Fallback to otp_release when OTP_VERSION is unavailable

---

.github/workflows/main.yml

Might not work with some elixir versions (should check) and it allows for flakyness but we're in a flaky domain.

Test retries with mix test --failed

---

lib/benchee/benchmark/runner.ex
lib/benchee/output/benchmark_printer.ex
lib/benchee/relative_statistics.ex
lib/benchee/statistics.ex
lib/benchee/utility/file_creation.ex
test/benchee/suite_test.exs

https://erlangforums.com/t/in-erlang-otp-27-0-0-will-no-longer-be-exactly-equal-to-0-0/2586

chore(Elixir): fix compiler warnings for elixir 1.16

---

CHANGELOG.md
lib/benchee/relative_statistics.ex
test/benchee/relative_statistics_test.exs

It used to rely on the inputs being there and then working based off on them - too bad, if we use `Benchee.load` then there are no inputs to go off, but they are still in the scenarios to work with them. Needs some care to preserve order which looks odd but couldn't find a better way.

Fix relative statistics calculations

---

README.md

Introduce known issues and point people to it

---

CHANGELOG.md
lib/benchee/configuration.ex
lib/benchee/formatter.ex
lib/benchee/statistics.ex
test/benchee/configuration_test.exs
test/benchee/formatter_test.exs
test/benchee/formatters/tagged_save_test.exs
test/benchee/statistics_test.exs
test/benchee_test.exs

Should combat memory consumption issues caused by sending too much data to processes.
edit: To highlight the severeness of this:
* there is a benchmark I'm working on that I almost couldn't run before this as my 32GB of RAM would not be enough
* benchmark is this one: https://github.com/PragTob/tco_elixir
* it also hung forever before calculating statistics and running the formatters
* In that benchmark I used `:save` to compare performance across elixir version, before this PR each individual save file was 200+MB. With this MR, it's 1MB (as it removes the data from formatters and `:save` is a formatter under the hood). The file size isn't the major thing, but it illustrates how much memory we save and how much time copying memory we avoid. 
I wanna write up all of this in like 2 blog …

Memory usage optimization / avoid sending unneeded data to parallel processing

---

lib/benchee/benchmark.ex
lib/benchee/benchmark/benchmark_config.ex
lib/benchee/benchmark/runner.ex
lib/benchee/benchmark/scenario_context.ex
lib/benchee/configuration.ex
lib/benchee/profile.ex
test/benchee/benchmark_test.exs

Fixes #412 - but basically the `Config` holds `inputs` and that can be a hell loat of data to send along with every benchmark.
In a benchmark with 16 scenarios and huge inputs we now save ourselves copying that potentially huge data structure a whopping 16 times to our benchmarking processes for no reason whatsoever (the scenarios already hold the `input`).

Introduce `BenchmarkConfig` to selectively use config in benchmark

---

CHANGELOG.md
lib/benchee/formatter.ex

This reverts commit dfa6987a5e1c8db0a6629fad70127097d3bc9577.
It turned out that the parallel processing wasn't the issue with memory consumption we faced but instead copying data to processes.
See:
* #408
* #414
* https://pragtob.wordpress.com/2023/12/18/careful-what-data-you-send-or-how-to-tank-your-performance-with-task-async/

Revert "Introduce optional sequential_output/2 callback"

---

CHANGELOG.md
lib/benchee/conversion/count.ex
lib/benchee/conversion/deviation_percent.ex
lib/benchee/conversion/duration.ex
lib/benchee/conversion/format.ex
lib/benchee/conversion/memory.ex
lib/benchee/conversion/scale.ex
lib/benchee/output/benchmark_printer.ex
test/benchee/conversion/duration_test.exs
test/benchee/output/benchmark_printer_test.exs

This is #373 - as I didn't take care of it for too long/forever I'm integrating it myself and polishing it up.
Follow ups:

Drobnyd human friendlier format

---

lib/benchee/system.ex
test/benchee/system_test.exs

Associated PR for issue: https://github.com/bencheeorg/benchee/issues/421
Added calls as appropriate to kstat and prtconf to produce intended results.
This was specifically tested on SmartOS base-64-trunk 20231113

Added initial Solaris support to Benchee.System

---

lib/benchee/conversion/scale.ex

Hi!
This the same fix as https://github.com/bencheeorg/benchee/commit/2d56fba7e9df361943e1342889c816cc2c6056f4.
It fixes the following warning:
```elixir
warning: using map.field notation (without parentheses) to invoke function Benchee.Conversion.Count.base_unit() is deprecated, you must add parentheses instead: remote.function()
(benchee 1.2.0) lib/benchee/conversion/scale.ex:165: Benchee.Conversion.Scale.do_best_unit/3
(benchee 1.2.0) lib/benchee/conversion.ex:63: Benchee.Conversion.units/2
...
````
I think there is no occurrence left.
Cheers!

Fix another deprecation warning on missing parenthesis

---

lib/benchee/system.ex
test/benchee/system_test.exs

This is in relation to #442 - we'd previously fail if a command wasn't available at all which definitely is wrong.
This is a quicker fix vs. getting better CPU/memory information from elsewhere.

Make system gathering more resilient

---

.github/workflows/main.yml

Removes the duplication on the elixir versions that was error prone and needed updating.
Also would allow us to run it on more versions.
With friendly inspiration from mint:
https://github.com/elixir-mint/mint/blob/90ee9fdb27c0d52b374b8d689c54d8559b2bb57c/.github/workflows/main.yml

Make when to run lint/dialyzer more flexible

---

.gitignore
.tool-versions

Kinda changed my opinion on this, it became annoying to upgrade patch versions on my other systems just to be in sync. Since this is a library that should work on _many_ versions and runs CI that way there is no need for strict enforcement.

gitignore .tool-versions

---

diagrams/component.pu
diagrams/container.pu
diagrams/context.pu

I've modified the diagrams source with your feedback from issue #454 and added them to the top-level folder `diagrams`.

Added new C4 architecture diagrams

---

test/benchee_test.exs

The escript building test didn't use to restore the proper working directory. This caused `mix coveralls.html` not to work as it got confused looking up the html template to render in the dependencies.

Get back to current working path after test finishes

---

test/benchee_test.exs

Sometimes the iex(2)> (at least on CI) is sent together with the output of the benchmark/the benchmark suite. That caused it to be flakey.
This change should accommodate for that and lead to less flakey results.

Tackle flakey iex warning test
