README.md
lib/benchee/benchmark.ex
lib/benchee/config.ex
samples/one_fast_fun_no_warnings.exs
test/benchee/benchmark_test.exs
test/benchee_test.exs

Configurable warnings

---

lib/benchee/statistics.ex
lib/benchee/utility/map_value.ex

implement parallel map_values for statistics

---

lib/benchee.ex

just some beautification suggested by @h4cc

pipeify do_run

---

.travis.yml
CHANGELOG.md
lib/benchee.ex
lib/benchee/benchmark.ex
lib/benchee/config.ex
lib/benchee/formatters/console.ex
lib/benchee/statistics.ex
lib/benchee/suite.ex
lib/benchee/system.ex
mix.exs
test/benchee/benchmark_test.exs
test/benchee/formatters/console_test.exs
test/benchee/statistics_test.exs
test/benchee/suite_test.exs
test/benchee/system_test.exs

Dialyzer setup for type checking

---

CHANGELOG.md
lib/benchee/utility/map_value.ex

Wait infinitely for statistic computation so it does not time out

---

lib/benchee/conversion/scale.ex
lib/benchee/formatters/console.ex
lib/benchee/system.ex
test/benchee/benchmark_test.exs
test/benchee/conversion/count_test.exs
test/benchee/conversion/duration_test.exs
test/benchee/formatters/console_test.exs
test/benchee/output/benchmark_printer_test.exs
test/benchee/statistics_test.exs
test/benchee/suite_test.exs
test/benchee/utility/file_creation_integration_test.exs

Drop 1.2 support - cleanups

---

CHANGELOG.md
lib/benchee/conversion/duration.ex
lib/benchee/conversion/format.ex
lib/benchee/output/benchmark_printer.ex
test/benchee/conversion/duration_test.exs
test/benchee/output/benchmark_printer_test.exs

Scale durations of printed configurations

---

lib/benchee/output/benchmark_printer.ex
lib/benchee/system.ex
test/benchee/output/benchmark_printer_test.exs
test/benchee/system_test.exs

This will eventually be used to improve the output when running
benchmarks in Benchee. For now, though, this is pretty much just the
rough outline of how to get this information so I can get some feedback
on if I'm on the right path according to what @PragTob was envisioning.
Eventually this will close #63.

Add functions for additional sytem information

---

lib/benchee/system.ex
test/benchee/system_test.exs

Now that all three platforms have been implemented, I think I've found
a good, readable and DRY way of modeling this process. This commit
includes that refactoring, and also implements my best guess of a
working Windows implementation.
@OvermindDL1, if you have time to give this a test, let me know how
it looks!
@PragTob Since this also includes the refactorings that we mentioned
in #78, I think we can just close that one and go with this PR, right?

Adding windows info

---

lib/benchee.ex
test/benchee_test.exs

Idea taken from https://elixirforum.com/t/writing-a-library-for-use-in-both-elixir-and-erlang/2900/5?u=pragtob
basically: have two top level modules that implement the same functions, so that new functions just get added to `Benchee.Impl` and I don't have to worry about them getting out of sync.

Erlang module style

---

.travis.yml
test/support/test_helpers.ex

Just making sure we do this so we're compatible with the new versions.

Add new OTP and Elixir version to CI config

---

.travis.yml

* Running in VM environment, my favorite trick: keathley/wallaby#186

More RAM for dialyzer

---

lib/benchee/system.ex
test/benchee/system_test.exs

* Some random adjustments such as describe blocks and regex into
a module attribute

General case test for cpu info

---

lib/benchee.ex

* suggestion from @josevalim
https://github.com/PragTob/benchee/commit/b3ddbc132e641cdf1eec0928b322ced1dab8553f#commitcomment-23381474

Avoid __using__ for erlang interface, simpler iteration and def

---

README.md
lib/benchee/system.ex
samples/flat_map.exs
samples/multiple_map.exs
samples/parallel_process.exs
samples/run.exs
test/benchee/system_test.exs

I added float rounding for available memory and added test for that

Limit reported precision for memory

---

README.md

Thought it might be worth mentioning :)

mention slack channel

---

.travis.yml
mix.exs
mix/tasks.ex

* Basically all the builds have been red :'(

Do not fail when coveralls fails to upload

---

lib/benchee/benchmark.ex
lib/benchee/benchmark/runner.ex
lib/benchee/benchmark/scenario.ex
lib/benchee/benchmark/scenario_context.ex
lib/benchee/configuration.ex
test/benchee/benchmark/runner_test.exs
test/benchee/benchmark_test.exs
test/benchee_test.exs
test/support/test_helpers.ex

* Still need to fix & test that they are run with every invocation
when we have to repeat the invocations
* Need to add `after_each:`
ref: #59

First sketch of before hooks in Benchee :rocket:

---

lib/benchee/benchmark/runner.ex
test/benchee/benchmark/runner_test.exs
test/benchee_test.exs

Pass return values of the main function to the after_each hook

---

README.md
lib/benchee/configuration.ex
lib/benchee/conversion/scale.ex
lib/benchee/formatters/console.ex
test/benchee/configuration_test.exs
test/benchee/formatters/console_test.exs

Make unit_scaling a top level configuration option

---

samples/length.exs

How long does it take to count the elements of a list?

---

lib/benchee/conversion/memory.ex
lib/benchee/system.ex
test/benchee/conversion/memory_test.exs

Memory conversion

---

README.md

* already includes not yet merged `after_scenario` and its handling
* this is basically a blog post _sigh_ - you only realize how
complex the system you built in your head is when you document
it :)
* honestly I'm on my way to the beach now so didn't get to reading
it through another time myself, sorry :D
* Feedback very welcome, on strucutre/order/content whatever - I
want this documentation to be as good as it can get because
that's what a proper library should be doing.
**Fair warning, diff is a semi long read**

Documentation for the new hooks system

---

lib/benchee/conversion.ex
lib/benchee/formatters/console.ex
test/benchee/conversion_test.exs

Make the function finding best units available for plugins

---

README.md
lib/benchee.ex
lib/benchee/configuration.ex
lib/benchee/formatter.ex
samples/formatters.exs
test/benchee_test.exs
test/support/fake_formatter.ex

Formatters as modules and parallel execution

---

lib/benchee/statistics.ex

Adds function for calculating additional percentiles, such as those required for creating box plots. See #57. The additional percentiles are added to the statistics for each scenario, so this function must be called after `statistics/1`.
The box plots need specifically the first and third quartiles, which you can get by passing `[25, 75]` as the `percentile_ranks`.

Add additional percentiles function to Statistics

---

lib/benchee/output/benchmark_printer.ex
test/benchee/output/benchmark_printer_test.exs

Fix estimated run times being too high

---

README.md

I had been working on this so long ago that I forgot I already wrote documentation :thinking: 
Tried to improve upon it a bit :)

Extend store & load documenation

---

test/benchee/benchmark_test.exs

We've got a lot of formatting to do. Might as well start with some of
our low churn code! I was thinking we'd take it file by file like they
did with the Elixir codebase itself instead of trying to do one huge
piece.
Once we have everything formatted then we can add a formatter check to
CI so we stay that way.

Format Benchee.BenchmarkTest

---

lib/benchee/utility/file_creation.ex
test/benchee/utility/file_creation_integration_test.exs

Builds on top of #181
(adds more integrationy test and makes file opening fail)

Gfvcastro update to filename pattern

---

CHANGELOG.md
lib/benchee/utility/file_creation.ex
mix.exs
test/benchee/utility/file_creation_integration_test.exs

Cherry picked etc.
Tobi tries to be a good maintainer. :grin:

0.12.1 release

---

lib/benchee/benchmark/runner.ex
samples/macro_benchmark.exs
test/benchee/benchmark/runner_test.exs
test/benchee_test.exs

I'm not sure what else we want to test for here, but this basic test
should address the first part of #3. Is there anything further we
really want to test around macros here?

Add test to ensure everything works with macros

---

.tool-versions
CHANGELOG.md
lib/benchee/statistics.ex
test/benchee/statistics_test.exs

Finally learned why that's the case and it's called
Bessel's Correction
https://en.wikipedia.org/wiki/Bessel's_correction

Use correct formula for standard deviation of a sample

---

lib/benchee/benchmark/runner.ex
lib/benchee/formatters/console/memory.ex
lib/benchee/formatters/console/run_time.ex
lib/benchee/output/benchmark_printer.ex
test/benchee/benchmark/runner_test.exs
test/benchee_test.exs

Was perusing the code while waiting for the appveyor builds,
this is the result :)
I'll add some comments to show what I thought and make them less "random" :)

Refactorings to shorter methods/reduced duplication/style

---

samples/memory_breaker.exs
test/benchee/benchmark/measure/memory_test.exs
test/benchee_test.exs
test/support/bench_keyword.ex

Follow up to #213
Decided to inline the relevant parts of it to the test suite as
it highlighted so many problems. One of which I don't know how
to test. Moreover, with it highlighting so many problems it might
highlight them again later.
Also removed some dead code from said benchmark and added
attribution to @michalmuskala

Memory breaker integration test

---

lib/benchee/formatters/tagged_save.ex
test/benchee/formatters/tagged_save_test.exs

Replaces #215 - slightly different approach.

Zachdaniel fix tag name

---

lib/benchee/benchmark/measure/memory.ex

#262 reminded me of just how strange this code might be to people new to the code base and also to myself after a couple of months. This general information should help :)
@devonestes anything important I missed?

References for memory measurements to grasp it

---

lib/benchee.ex

To automatically show delegated functions gotta do
elixir-lang/ex_doc#902 :)

Remove testing related functions and show delegates

---

lib/benchee/system.ex
test/benchee/benchmark/runner_test.exs
test/benchee/system_test.exs
test/benchee_test.exs

When moving all this into a new library all of these will be
public there.

Minimize System Interface by adjusting tests

---

lib/benchee/benchmark.ex
lib/benchee/benchmark/collect/memory.ex
lib/benchee/benchmark/collect/native_time.ex
lib/benchee/benchmark/collect/time.ex
lib/benchee/benchmark/hooks.ex
lib/benchee/benchmark/repeated_measurement.ex
lib/benchee/benchmark/scenario_context.ex
lib/benchee/collection_data.ex
lib/benchee/configuration.ex
lib/benchee/conversion/count.ex
lib/benchee/formatters/console.ex
lib/benchee/formatters/console/helpers.ex
lib/benchee/scenario.ex
lib/benchee/statistics/mode.ex

Added some missing typespecs to help dialyzer in its tracks.

Such types many wow :)

---

README.md

Warn about MacOS measuring inaccuracies

---

CHANGELOG.md
mix.exs

Still a long while to go - we need README sections for all the
new features.

Basic version change and changelog

---

README.md

@pablocostass if you had a bit of time to review these it'd be appreciated but of course not needed :)

Add more comprehensive profiler docs

---

lib/benchee/benchmark/collect.ex
lib/benchee/benchmark/collect/profile.ex
lib/benchee/benchmark/run_once.ex
lib/benchee/benchmark/runner.ex
lib/benchee/profile.ex
test/benchee/profile_test.exs
test/benchee_test.exs
test/support/test_helpers.ex

Realized while writing the docs that we don't seem to take into account functions that take arguments or running hooks at all :sweat_smile: 
so far these are just failing tests.

Failing tests for profiling not working with hooks or inputs & now also fixing it

---

lib/benchee/benchmark/repeated_measurement.ex
test/test_helper.exs

debug macos failures & fix them

---

.github/workflows/main.yml

Migrate GitHub Action to erlef/setup-beam

---

.github/workflows/main.yml
.tool-versions

Then if it does, merge https://github.com/bencheeorg/benchee/pull/390 to fix it all :)

CI against the elixir rc to see that our CI catches all

---

lib/benchee/system.ex
test/benchee/system_test.exs
test/benchee_test.exs
test/fixtures/escript/.gitignore
test/fixtures/escript/README.md
test/fixtures/escript/lib/escript.ex
test/fixtures/escript/mix.exs
test/fixtures/escript/mix.lock
test/fixtures/escript/test.sh

see #384 
But basically, we can't look up elixir and hence can't do protocol consolidation

Fix escript

---

CHANGELOG.md
lib/benchee/output/benchmark_printer.ex
lib/benchee/suite.ex
lib/benchee/system.ex
test/benchee/benchmark/runner_test.exs
test/benchee/output/benchmark_printer_test.exs
test/benchee/suite_test.exs
test/benchee/system_test.exs

Adding fields was painful before and I missed where I should add them, this should make it easier to have the compiler check it for you.

Make System a struct
